apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: managed-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managed-rbac
subjects:
- kind: ServiceAccount
  name: managed-rbac-sa
  namespace: open-cluster-management
